# WhatATheme
markdown: kramdown

# URL of the Site
url: 'https://deepdivesecurity.ca'
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: DeepDiveSecurity
# Description of the Site
description: 
# URL of Image of the Site
site-image: /assets/images/meta.jpg
# Keywords of the Site
site-keywords: Security, Guidance, Docker, Kubernetes, Cloud, AWS, GCP, Azure, Architecture
# URL for the Image of custom Favicon
favicon-url: /assets/images/favicon.ico

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: /assets/images/main_background.jpeg

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: deepdivesec@outlook.com
facebook_username: 
twitter_username: 
instagram_username: 
linkedin_username:
github_username: arkdevelop
youtube_channel_id:
reddit_username:
behance_username:
dribbble_username:
spotify_username:

# Google Analytics
google-analytics: UA-119740518-1

# Disqus
disqus-shortname: deepdivesecurity

# Name of the Author
author-name: arkdevelopment
# URL for the Image of the Author
author-image: /assets/images/logo.png
# 60 Words About the Author
author-about: Deep Dive Security is comprised of multiple years of technical experience in a cloud security role with a proven track record in security assessments and authorization. Adept at researching, documenting, and communicating security best practice guidance, Deep Dive Security aims to improve project architectures to ensure a strong organization security posture. See the Blog page for security guidance and best practices.
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/arkdevelop

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed
  - jekyll-sitemap

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
