# DeepDiveSecurity
markdown: kramdown

# URL of the Site
url: 'https://deepdivesecurity.ca'
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Deep Dive Security
# Description of the Site
description: Make a splash in your security.
# URL of Image of the Site
site-image: /assets/img/meta.jpg
# Keywords of the Site
site-keywords: Security, Best-practices, Guidance, Docker, Kubernetes, Cloud, AWS, GCP, Azure, Architecture
# URL for the Image of custom Favicon
favicon-url: /assets/img/favicon.ico

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
address: Not yet set
email: deepdivesec@outlook.com
facebook_username: 
twitter_username: deepdivesec404
instagram_username: 
linkedin_username:
github_username: arkdevelop
youtube_channel_id:
reddit_username:
behance_username:
dribbble_username:
spotify_username:

# Google Analytics
google-analytics: UA-119740518-1

# Disqus
disqus-shortname: deepdivesecurity

# Name of the Author
author-name: DeepDiveSecurity
# URL for the Image of the Author
author-image: /assets/img/logo.png
# 60 Words About the Author
author-about: Deep Dive Security has over 3 years of experience in a cloud security role with a proven track record in security assessments and authorization, cloud security, and DevSecOps. We are adept at researching, documenting, and promoting security best practices in addition to being proficient in conducting thorough security assessments, threat modelling, and reviews of services and project architectures using industry standards like NIST, CSA, Mitre, OWASP, and IETF standards. Through this, Deep Dive Security is able to devise a strong organization-wide security posture.
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/arkdevelop
# Author years of experience
author-experience: 3

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

# Blog pagination
paginate: 5
paginate_path: "/blog/page:num/"

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/